dist: trusty
language: java
jdk: oraclejdk8
services:
  - elasticsearch
before_install:
  - chmod +x mvnw
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.12.0-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
before_script:
  - sleep 10
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/jacoco.xml
  
